### ISSUE TITLE
libsodium fails to load on older versions of macOS

### ISSUE THREAD

**Issue by samuelmaddock** [samuelmaddock/metastream#27]
- Metastream Version: 0.1.2
- OS Version: macOS 10.10.5 Yosemite

Steps to Reproduce:

1. Open Metastream app.

Observe JavaScript error:
```
Uncaught Exception:
Error: dlopen(/Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/node-67.node, 1): Library not loaded: @loader_path/libsodium.dylib
  Referenced from: /Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/node-67.node
  Reason: no suitable image found.  Did find:
    /Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib: code signature invalid for '/Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib'

    /Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib: code signature invalid for '/Applications/Metastream.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib'

    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:596:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at load (/Applications/Metastream.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:13:10)
    at /Applications/Metastream.app/Contents/Resources/app.asar/node_modules/sodium-native/index.js:1:186
```

**Comment by samuelmaddock** [comment]
I've gotten a report that this can be fixed by installing libsodium using brew. There are likely some missing dependencies that get installed. [Here's a fix for the problem](http://macappstore.org/libsodium/).
