### ISSUE TITLE
Crash on join via Friendcode.

### ISSUE THREAD

**Issue by SoarinSorin** [samuelmaddock/metastream#38]
```
Error: stream.push() after EOF
    at readableAddChunk (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\readable-stream\lib\_stream_readable.js:264:1)
    at Decoder.module.exports../node_modules/swarm-peer-server/node_modules/readable-stream/lib/_stream_readable.js.Readable.push (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\readable-stream\lib\_stream_readable.js:238:1)
    at Decoder.module.exports../node_modules/swarm-peer-server/node_modules/readable-stream/lib/_stream_transform.js.Transform.push (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\readable-stream\lib\_stream_transform.js:146:1)
    at Decoder.module.exports../node_modules/swarm-peer-server/node_modules/length-prefixed-stream/decode.js.Decoder._push (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\length-prefixed-stream\decode.js:28:1)
    at Decoder.module.exports../node_modules/swarm-peer-server/node_modules/length-prefixed-stream/decode.js.Decoder._parseMessage (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\length-prefixed-stream\decode.js:57:1)
    at Decoder.module.exports../node_modules/swarm-peer-server/lib/socket.js.Decoder._transform (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\lib\socket.js:22:1)
    at Decoder.module.exports../node_modules/swarm-peer-server/node_modules/readable-stream/lib/_stream_transform.js.Transform._read (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\readable-stream\lib\_stream_transform.js:182:1)
    at Decoder.module.exports../node_modules/swarm-peer-server/node_modules/readable-stream/lib/_stream_transform.js.Transform._write (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\readable-stream\lib\_stream_transform.js:170:1)
    at doWrite (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\readable-stream\lib\_stream_writable.js:406:52)
    at writeOrBuffer (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\readable-stream\lib\_stream_writable.js:395:1)
    at Decoder.module.exports../node_modules/swarm-peer-server/node_modules/readable-stream/lib/_stream_writable.js.Writable.write (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\webpack:\node_modules\swarm-peer-server\node_modules\readable-stream\lib\_stream_writable.js:322:1)
    at Connection.ondata (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at addChunk (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\Sorin\AppData\Local\Programs\metastream\resources\app.asar\node_modules\readable-stream\lib\_stream_readable.js:278:11)
```

**Comment by samuelmaddock** [comment]
Is this a consistent crash or did it just happen once? And which version of Metastream are you using?

**Comment by samuelmaddock** [comment]
Closing as the Electron app will soon be deprecated by #94.
